ch[1]="abdomen black"
ch[2]="abdomen red or part red"
ch[3]="abdomen with orange bands"
ch[4]="abdomen metallic blue"
ch[5]="face marks yellow"
ch[6]="face marks cream or white"
ch[7]="no face marks"
ch[8]="clypeus with pale mark"
ch[9]="clypeus red or part red"
ch[10]="clypeus without pale colour"
ch[11]="scutellum yellow"
ch[12]="scutellum same as scutum"
ch[13]="collar with pale marks"
ch[14]="collar without pale marks"
ch[15]="tubercle coloured"
ch[16]="tubercle not coloured"
ch[17]="length 5 mm or less"
ch[18]="length 5-8 mm"
ch[19]="length 9 mm or more"
chcol[0]=0
chcol[1]=4
chcol[2]=7
chcol[3]=10
chcol[4]=12
chcol[5]=14
chcol[6]=16
chcol[7]=19