mch[1]="abdomen black"
mch[2]="abdomen red or part red"
mch[3]="abdomen with orange bands"
mch[4]="abdomen metallic blue"
mch[5]="face marks yellow"
mch[6]="face marks cream or white"
mch[7]="scutellum yellow"
mch[8]="scutellum same as scutum"
mch[9]="scapes broad or swollen"
mch[10]="collar with pale marks"
mch[11]="collar without pale marks"
mch[12]="tubercle coloured"
mch[13]="tubercle not coloured"
mch[14]="abdomen with spines or ridge"
mch[15]="length 4 mm or less"
mch[16]="length 4-7 mm"
mch[17]="length 7 mm or more"
mchcol[0]=0
mchcol[1]=4
mchcol[2]=6
mchcol[3]=8
mchcol[4]=9
mchcol[5]=11
mchcol[6]=13
mchcol[7]=14
mchcol[8]=17
